server:
  host: "0.0.0.0"
  port: 8080
  workers: 4
  timeout: 60

models:
  - name: "clip-vit-b-32"
    model_type: "clip"
    model_id: "openai/clip-vit-base-patch32"
    precision: "fp16"
    device: "cuda:0"
    default: true
    
  - name: "clip-vit-l-14"
    model_type: "clip"
    model_id: "openai/clip-vit-large-patch14"
    precision: "fp16"
    device: "cuda:1"
    
  - name: "clip-vit-b-16-plus-240"
    model_type: "open_clip"
    model_id: "laion/CLIP-ViT-B-16-plus-240"
    precision: "fp32"
    device: "cuda:0"
    
  - name: "siglip-base-patch16"
    model_type: "siglip"
    model_id: "google/siglip-base-patch16-224"
    precision: "fp16"
    device: "cuda:0"
    description: "SigLIP Base model with 224x224 inputs"

log_level: "INFO" 